name: Continuous Integration

on:
  push:
    paths:
      - 'JavaScript/**'  # Include the JavaScript folder and its subdirectories
      - 'TypeScript/**'   # Include the TypeScript folder and its subdirectories
      - '.github/workflows/jsBuild.yml'
  pull_request:
    paths:
      - 'JavaScript/**'  # Include the JavaScript folder and its subdirectories
      - 'TypeScript/**'   # Include the TypeScript folder and its subdirectories
      - '.github/workflows/jsBuild.yml'
          

jobs:
  build:
    name: Code style and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: ðŸ“¦ Install dependencies
        run: npm ci

      - name: ðŸ§ª Run all tests
        if: ${{ github.event_name == 'push' }}
        run: npm run test

      - name: ðŸ§ª Run tests for changed files only
        if: ${{ github.event_name == 'pull_request' }}
        run: npm run test-changed

      - name: ðŸ’„ Code style
        run: npm run style

  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: codespell-project/actions-codespell@master
        with:
          # file types to ignore
          skip: "*.json,*.yml,DIRECTORY.md"
          ignore_words_list: "ba,esy,yse,falsy"
